defaults:
  - _self_

data:
  parser:
    timeout: 10
    delay_between_requests: 0.5
    max_press_releases: 1000
  dataset_path: "data/cbr_news.csv"
  dvc_remote: "gdrive://your-google-drive-folder-id"

  max_length: 512
  batch_size: 16
  test_size: 0.2
  val_size: 0.1

  train_years: [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
  test_years: [2024, 2025]

  tokenizer_name: "cointegrated/rubert-tiny2"

  classes:
    - down
    - same
    - up