defaults:
  - _self_

data:
  run_parser: false
  parser:
    timeout: 10
    delay_between_requests: 0.5
    max_press_releases: 1000
  dataset_path: "data/cbr_news.csv"
  dvc:
    enabled: true
    remote:
      name: "s3remote"
      url: "s3://potseluevam/"
      region_name: "ru-central1"
      endpoint_url: "https://storage.yandexcloud.net/"
  max_length: 512
  batch_size: 16
  test_size: 0.2
  val_size: 0.1
  prediction_horizon: 5
  ruonia_threshold: 0.05

  train_years: [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
  test_years: [2024, 2025]

  tokenizer_name: "DeepPavlov/rubert-base-cased"

  classes:
    - down
    - same
    - up