defaults:
  - data
  - multitask_model
  - train
  - _self_

hydra:
  job:
    chdir: true
  run:
    dir: outputs/multitask/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/multitask/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

seed: 42
project_name: "cbr_news_multitask"
