defaults:
  - _self_

model:
  backbone: "DeepPavlov/rubert-base-cased"
  num_classes: 3  # up, down, same для RUONIA
  dropout: 0.1

  learning_rate: 2e-5
  weight_decay: 0.01
  warmup_steps: 100

  freeze_backbone: false
  num_frozen_layers: 0

  auxiliary_tasks:
    # - usd
    # - inflation
     - key_rate

  # Веса для loss функций
  auxiliary_weight: 0.3  # вес для auxiliary tasks
  main_weight: 1.0       # вес для главной задачи (ключевая ставка)
